# Page settings
baseurl = "localhost:1313"
title = "Antoine Nguyen - Développeur web"
languageCode = "fr-fr"
theme = "hugo-elate-theme"

[params]
  
  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = "Antoine Nguyen"
  description = "Portfolio"
  email = "antoine.ngu@outlook.fr"
  # Navigation
  [params.navigation]
    brand = "Antoine Nguyen"
    home = "Accueil"
    work = "Projets"
    testimonials = "Témoignages"
    services = "Loisirs"
    about = "Emplois"
    contact = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    [[menu.prepend]]
     url = "https://www.linkedin.com/in/nguyen-antoine/"
     name = "Linkedin"
     weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10
  
  # Hero section
  [params.hero]
    title = "Développeur web"
    subtitle = "Je me suis passioné pour le développement web il y a peu et je suis en constante évolution grâce à mon envie d'apprendre et à ma motivation. Je suis autonome et je suis à l'écoute des actualités du monde informatique ainsi que son évolution."
 
  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Passionate reader"
    description = 'From History, biographies, Science to "classicals", technology and thrillers, I read about 50 books per year.'
    url = "https://www.goodreads.com/user/show/71319762-thomas-sauvajon"
    button = "Goodreads profile"
    icon = "icon-book-open"
    img = "library.jpg"

  [[params.intro.item]]
    title = "Technology enthusiast"
    description = "Proactive learning and technology watch is of utmost importance in tech; that's why I am subscribed to newsletters, blogs, Twitter accounts and spend several hours a week reading about new and innovative stuff."
    url = "https://stackshare.io/tsauvajon"
    icon = "icon-puzzle"
    button = "Stackshare profile"
    img = "neons.jpg"

  [[params.intro.item]]
    title = "Active learner"
    description = "The best way to learn something is to try it. That's why I've built tens of weekend projects to try out technologies and concepts."
    url = "https://github.com/tsauvajon"
    button = "Github profile"
    icon = "icon-chemistry"
    img = "coding.jpg"


  # Projects section
  [params.work]
    enable = true
    title = "Projets"
    description = 'Tous mes projets sont sur ma <a href="https://github.com/nguyenantoine">page GitHub</a>.'
    footertext = '&#42; closed source'

    [[params.work.row]]
      img = "dati.png"
      alt = "dati.dalyo.com screenshot"
      url = "https://dati.dalyo.com/"
      title = "Dalyo DATI"
      subtitle = "Application web pour la gestion d'alerte pour les travailleurs isolés"

    [[params.work.row]]
      img = "ddm.png"
      alt = "ddm.dalyo.com screenshot"
      url = "https://ddm.dalyo.com/"
      title = "DDM"
      subtitle = "Dalyo Device Management - Application web pour la gestion de terminaux"

    [[params.work.row]]
      img = "anvil.png"
      alt = "anvil.dalyo.com screenshot"
      url = "https://anvil.dalyo.com/"
      title = "Anvil"
      subtitle = "Application web pour la gestion de fichier de configuration mobile"

  # Achievements section
  [params.testimonials]
    enable = true
    title = "Témoignages"
    description = "Voici quelques avis de mes précédentes expériences."

    [[params.testimonials.item]]
      quote = "&ldquo;Antoine est en alternance chez Penbase. Il a intégré l'équipe de développement Web. Il participe au développement d'un outil interne basé sur le framework Symfony. Ses connaissances en Php/Html/JS lui permette d'intervenir sur d'autres projets Web. Antoine est un développeur très motivé et s'est très facilement intégré au sein de l'équipe.&rdquo;"
      person = '<a href="https://www.linkedin.com/in/jeanbort/" target="_blank">Jean Bort</a> <span class="subtext">Chef de projet/Tuteur pour alternance et stage dans Penbase</span>'
      img = "penbase.png"
      alt = "Penbase, éditeur de solutions métiers pour mobiles"

    [[params.testimonials.item]]
      quote = "&ldquo;Antoine est en alternance chez Penbase. Il a intégré l'équipe de développement Web. Il participe au développement d'un outil interne basé sur le framework Symfony. Ses connaissances en Php/Html/JS lui permette d'intervenir sur d'autres projets Web. Antoine est un développeur très motivé et s'est très facilement intégré au sein de l'équipe.&rdquo;"
      person = '<a href="https://www.linkedin.com/in/nicolas-gagean-8184a7a2/" target="_blank">Nicolas Gagean</a> <span class="subtext">Directeur commercial dans Penbase</span>'
      img = "penbase.png"
      alt = "Penbase, éditeur de solutions métiers pour mobiles"

  #[params.testimonials.video]
  #  enable = true
  #  title = "Blockchain hackaton"
  #  icon = "icon-play2"
  #  url = "https://www.youtube.com/watch?v=K1XOHtFVnQgk"
   

  # Hobbies section
  [params.services]
    enable = true
    title = "Loisirs"
    description = "Avoir des moments libres est rafraîchissant"
    
    [[params.services.item]]
      title = "Voyages"
      description = "J'adore voyager partout dans le monde pour visiter les différentes cultures. J'ai voyagé aux États-Unis, en Angleterre, en Espagne, en Irlande, en Italie, aux Pays-Basn, au Vietnam, en Thailande et à Taïwan."      
      icon = "icon-map"
    
    [[params.services.item]]
      title = "Cartomagie"
      description = "Avec des amis ou pour la famille, je fais souvent des tours de magies de proximité avec des cartes. C'est ce qu'on appelle le close-up."
      icon = "icon-people"

    [[params.services.item]]
      title = "Musique"
      description = "Je joue de la guitare depuis plus de 5 ans."
      icon = "icon-music"

    [[params.services.item]]
      title = "Sports"
      description = "Je pratique des sports collectifs avec des amis de temps en temps comme le basket, le football, mais aussi des sports individuels comme le tennis, la natation et la musculation."      
      icon = "icon-badge"

  # Jobs section
  [params.about]
    enable = true
    title = "Emplois"
    description = "Mes expériences professionnelles"

    [[params.about.item]]
      name = "Penbase"
      position = "Développeur web - Symfony 3"
      description = "Développement, déploiement et maintenance d'une application web <a href=\"https://anvil.dalyo.com/\" target=\"_blank\">Anvil</a> avec le framework PHP **Symfony**. *2 ans d'alternance*."
      img = "penbase.png"
      alt = "Logo Penbase"
      social = [
        ["icon-twitter", "https://twitter.com/penbase"],
        ["icon-facebook", "https://www.facebook.com/Penbase/"],
        ["icon-linkedin", "https://www.linkedin.com/company/penbase/"],
        ["icon-globe", "https://www.penbase.com"]
      ]

    [[params.about.item]]
      name = "Penbase"
      position = "Développeur web PHP"
      description = "Maintenance d'applications web <a href=\"https://dati.dalyo.com/\" target=\"_blank\">Dalyo DATI</a> et <a href=\"https://ddm.dalyo.com/\" target=\"_blank\">DDM</a>. *2 fois pour job d'été*."
      img = "penbase.png"
      alt = "Logo Penbase"
      social = [
        ["icon-twitter", "https://twitter.com/penbase"],
        ["icon-facebook", "https://www.facebook.com/Penbase/"],
        ["icon-linkedin", "https://www.linkedin.com/company/penbase/"],
        ["icon-globe", "https://www.penbase.com"]
      ]

    [[params.about.item]]
      name = "Penbase"
      position = "Développeur web PHP"
      description = "Conception, développement et déploiement d'applications web <a href=\"https://dati.dalyo.com/\" target=\"_blank\">Dalyo DATI</a> et <a href=\"https://ddm.dalyo.com/\" target=\"_blank\">DDM</a> avec du **PHP** et **MySQL**. *Stagiaire pour fin d'étude*."
      img = "penbase.png"
      alt = "Logo Penbase"
      social = [
        ["icon-twitter", "https://twitter.com/penbase"],
        ["icon-facebook", "https://www.facebook.com/Penbase/"],
        ["icon-linkedin", "https://www.linkedin.com/company/penbase/"],
        ["icon-globe", "https://www.penbase.com"]
      ]


  # Counters section
  [params.counters]
    enable = true
    title = "Quelques chiffres ..."
    background = "city.jpg"

    [[params.counters.item]]
      description = "ans"
      icon = "icon-present"
      from = 0
      to = 23
      interval = 50
      speed = 2000

    [[params.counters.item]]
      description = "années d'expérience professionnelle"
      icon = "icon-briefcase"
      from = 0
      to = 3
      interval = 50
      speed = 2000

    [[params.counters.item]]
      description = "Année d'obtention du diplôme"
      icon = "icon-graduation"
      from = 1995
      to = 2019
      interval = 50
      speed = 2000

  # Contact section
  [params.contact]
    enable = true
    map = true
    form = true
    title = "Me contacter"
    description = ""
    
    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "34000 Montpellier (France)"],
        ["icon-phone", "(33) 6 10 76 27 02"],
        ["icon-envelope", "antoine.ngu@outlook.fr"],
        ["icon-globe", '<a href="https://nguyenantoine.github.io/" target="_blank">nguyenantoine.github.io</a>']
      ]

    name = "Nom"
    email = "Email"
    phone = "Téléphone"
    message = "Message"
    button = "Envoyer un message"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; Antoine Nguyen. All Rights Reserved.<br>Built with <a href="https://gohugo.io/">Hugo</a>. Stock photos from <a href="https://www.pexels.com">Pexels</a>. Template &copy; Elate <a href="http://freehtml5.co/" target="_blank">Free HTML5</a>. Hugo port by <a href="https://github.com/saey55" target="_blank">saey55</a>.'
    links = [
        ["icon-github", "https://github.com/NguyenAntoine"],
        #["icon-twitter", "https://twitter.com/NguyenAntoine"],
        #["icon-facebook", "https://www.facebook.com/NguyenAntoine"],
        ["icon-linkedin", "https://linkedin.com/in/nguyen-antoine"]
      ]
