# Page settings
baseurl = "nguyenantoine.github.io"
title = "Antoine Nguyen - Développeur web"
languageCode = "fr-fr"
theme = "hugo-elate-theme"

[params]

  custom_css = ["css/custom1.css"]

  # Meta
  author = "Antoine Nguyen"
  description = "Portfolio"
  email = "antoine.ngu@outlook.fr"
  # Navigation
  [params.navigation]
    brand = "Antoine Nguyen"
    home = "Accueil"
    work = "Projets"
    testimonials = "Témoignages"
    services = "Loisirs"
    about = "Emplois"
    contact = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order

    # prepended links
    [[menu.prepend]]
     url = "https://www.linkedin.com/in/nguyen-antoine/"
     name = "Linkedin"
     weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10

  # Hero section
  [params.hero]
    title = "Développeur web"
    subtitle = "Je me suis passioné pour le développement web il y a peu et je suis en constante évolution grâce à mon envie d'apprendre et à ma motivation. Je suis autonome et je suis à l'écoute des actualités du monde informatique ainsi que son évolution."

  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Gestion de projet"
    description = "De la conception d'une solution applicative à l'analyse des besoins, je peux construire un projet que ce soit avec un suivi itératif avec les méthodes Agiles ou que ce soit avec des spécifications dans un cahier des charges."
    icon = "icon-book-open"
    img = "management.jpg"

  [[params.intro.item]]
    title = "Web"
    description = "En constante apprentissage, je suis passionné par les technologies du web. Je me concentre sur des développements avec des frameworks PHP comme Symfony, mais aussi avec des frameworks JavaScript comme VueJS."
    icon = "icon-docs"
    img = "coding.jpg"

  [[params.intro.item]]
    title = "DevOps"
    description = "En fluidifiant les développements et les tests, je sais mettre en place de l'intégration continue, avec Jenkins, avec un environnement similaire en production en utilisant la technologie des conteneurs Docker."
    icon = "icon-screen-desktop"
    img = "devops.jpg"


  # Projects section
  [params.work]
    enable = true
    title = "Projets"
    description = 'Tous mes projets sont utilisés et sont en production.'
    footertext = '&#42; sources privés'

    [[params.work.row]]
      img = "dati.png"
      alt = "dati.dalyo.com screenshot"
      url = "https://dati.dalyo.com/"
      title = "Dalyo DATI*"
      subtitle = "Application web pour la gestion d'alertes pour les travailleurs isolés"

    [[params.work.row]]
      img = "ddm.png"
      alt = "ddm.dalyo.com screenshot"
      url = "https://ddm.dalyo.com/"
      title = "Dalyo Device Manager*"
      subtitle = "Application web pour la gestion de terminaux des clients Penbase"

    [[params.work.row]]
      img = "anvil.png"
      alt = "anvil.dalyo.com screenshot"
      url = "https://anvil.dalyo.com/"
      title = "Anvil*"
      subtitle = "Application web pour la gestion de fichiers de configuration mobile"

    [[params.work.row]]
      img = "dch.png"
      alt = "dch.dalyo.com screenshot"
      url = "https://dch.dalyo.com/"
      title = "Dalyo Customer Hub*"
      subtitle = "Application web pour la gestion des informations clients"

    [[params.work.row]]
      img = "bambou.png"
      alt = "bambou.nguyenantoine.com screenshot"
      url = "https://bambou.nguyenantoine.com/"
      title = "Le Bambou"
      subtitle = "Site vitrine pour le traiteur Le Bambou à Montpellier"

    [[params.work.row]]
      img = "JSM.png"
      alt = "jeusetetmatch.nguyenantoine.com screenshot"
      url = "https://jeusetetmatch.nguyenantoine.com/"
      title = "Jeu Set et Match"
      subtitle = "Application web de tennis pour le scorage de points en temps réel"

  # Achievements section
  [params.testimonials]
    enable = true
    title = "Témoignages"
    description = "Voici quelques avis de mes précédentes expériences."

    [[params.testimonials.item]]
      quote = "&ldquo;Antoine est en alternance chez Penbase. Il a intégré l'équipe de développement Web. Il participe au développement d'un outil interne basé sur le framework Symfony. Ses connaissances en Php/Html/JS lui permette d'intervenir sur d'autres projets Web. Antoine est un développeur très motivé et s'est très facilement intégré au sein de l'équipe.&rdquo;"
      person = '<a href="https://www.linkedin.com/in/jeanbort/" target="_blank">Jean Bort</a> <span class="subtext">Chef de projet/Tuteur pour alternance et stage dans Penbase</span>'
      img = "penbase.png"
      alt = "Penbase, éditeur de solutions métiers pour mobiles"

    [[params.testimonials.item]]
      quote = "&ldquo;Antoine travaille chez Penbase en alternance, comme développeur Web. Il a participé à l'élaboration du produit Dalyo DATI, une application mobile de PTI/DATI, en développant l'interface web permettant de gérer la solution. Ses qualités lui ont permis de s'intégrer rapidement à l'équipe : motivé, à l'écoute, autonome, compétent. Antoine est en capacité de conduire un projet innovant et de mettre en oeuvre de nouvelles fonctionnalités à partir de spécifications fonctionnelles.&rdquo;"
      person = '<a href="https://www.linkedin.com/in/nicolas-gagean-8184a7a2/" target="_blank">Nicolas Gagean</a> <span class="subtext">Directeur commercial dans Penbase</span>'
      img = "penbase.png"
      alt = "Penbase, éditeur de solutions métiers pour mobiles"

  #[params.testimonials.video]
  #  enable = true
  #  title = "Blockchain hackaton"
  #  icon = "icon-play2"
  #  url = "https://www.youtube.com/watch?v=K1XOHtFVnQgk"


  # Hobbies section
  [params.services]
    enable = true
    title = "Loisirs"
    description = "Avoir des moments libres est rafraîchissant"

    [[params.services.item]]
      title = "Voyages"
      description = "J'adore voyager partout dans le monde pour visiter les différentes cultures. J'ai voyagé aux États-Unis, en Angleterre, en Espagne, en Irlande, en Italie, en Allemagne, aux Pays-Bas, au Vietnam, en Thailande et à Taïwan."
      icon = "icon-map"

    [[params.services.item]]
      title = "Cartomagie"
      description = "Avec des amis ou pour la famille, je fais souvent des tours de magies de proximité avec des cartes. C'est ce qu'on appelle le close-up.<br><br>"
      icon = "icon-magic-wand"

    [[params.services.item]]
      title = "Sports"
      description = "Je pratique des sports collectifs avec des amis de temps en temps comme le basket, le football, mais aussi des sports individuels comme le tennis, la natation et la musculation."
      icon = "icon-badge"

    [[params.services.item]]
      title = "Musique"
      description = "Je joue de la guitare depuis plus de 5 ans."
      icon = "icon-music"

  # Jobs section
  [params.about]
    enable = true
    title = "Emplois"
    description = "Mes expériences professionnelles"

    [[params.about.item]]
      name = "Penbase"
      position = "Développeur web - Symfony 3"
      description = "Développement, déploiement et maintenance d'une application web <a href=\"https://anvil.dalyo.com/\" target=\"_blank\">Anvil</a> avec le framework PHP **Symfony**. *2 ans d'alternance*."
      img = "penbase.png"
      alt = "Logo Penbase"
      social = [
        ["icon-twitter", "https://twitter.com/penbase"],
        ["icon-facebook", "https://www.facebook.com/Penbase/"],
        ["icon-linkedin", "https://www.linkedin.com/company/penbase/"],
        ["icon-globe", "https://www.penbase.com"]
      ]

    [[params.about.item]]
      name = "Penbase"
      position = "Développeur web PHP"
      description = "Maintenance d'applications web <a href=\"https://dati.dalyo.com/\" target=\"_blank\">Dalyo DATI</a> et <a href=\"https://ddm.dalyo.com/\" target=\"_blank\">DDM</a>. *2 fois pour job d'été*."
      img = "penbase.png"
      alt = "Logo Penbase"
      social = [
        ["icon-twitter", "https://twitter.com/penbase"],
        ["icon-facebook", "https://www.facebook.com/Penbase/"],
        ["icon-linkedin", "https://www.linkedin.com/company/penbase/"],
        ["icon-globe", "https://www.penbase.com"]
      ]

    [[params.about.item]]
      name = "Penbase"
      position = "Développeur web PHP"
      description = "Conception, développement et déploiement d'applications web <a href=\"https://dati.dalyo.com/\" target=\"_blank\">Dalyo DATI</a> et <a href=\"https://ddm.dalyo.com/\" target=\"_blank\">DDM</a> avec du **PHP** et **MySQL**. *Stage de fin d'étude*."
      img = "penbase.png"
      alt = "Logo Penbase"
      social = [
        ["icon-twitter", "https://twitter.com/penbase"],
        ["icon-facebook", "https://www.facebook.com/Penbase/"],
        ["icon-linkedin", "https://www.linkedin.com/company/penbase/"],
        ["icon-globe", "https://www.penbase.com"]
      ]


  # Counters section
  [params.counters]
    enable = true
    title = "Quelques chiffres ..."
    background = "city.jpg"

    [[params.counters.item]]
      description = "ans"
      icon = "icon-present"
      from = 0
      to = 23
      interval = 50
      speed = 2000

    [[params.counters.item]]
      description = "années d'expérience professionnelle"
      icon = "icon-briefcase"
      from = 0
      to = 3
      interval = 50
      speed = 2000

    [[params.counters.item]]
      description = "Année d'obtention du diplôme"
      icon = "icon-graduation"
      from = 1995
      to = 2019
      interval = 50
      speed = 2000

    [[params.counters.item]]
      description = "pays visités"
      icon = "icon-globe"
      from = 0
      to = 10
      interval = 50
      speed = 2000

  # Contact section
  [params.contact]
    enable = true
    map = true
    form = true
    title = "Me contacter"
    description = ""

    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "34000 Montpellier (France)"],
        ["icon-phone", "(33) 6 10 76 27 02"],
        ["icon-envelope", "antoine.ngu@outlook.fr"],
        ["icon-globe", '<a href="https://nguyenantoine.com/" target="_blank">nguyenantoine.github.io</a>']
      ]

    name = "Nom"
    email = "Email"
    phone = "Téléphone"
    message = "Message"
    button = "Envoyer un message"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; Antoine Nguyen. All Rights Reserved.<br>Built with <a href="https://gohugo.io/">Hugo</a>. Stock photos from <a href="https://www.pexels.com">Pexels</a>. Template &copy; Elate <a href="http://freehtml5.co/" target="_blank">Free HTML5</a>. Hugo port by <a href="https://github.com/saey55" target="_blank">saey55</a>.'
    links = [
        ["icon-github", "https://github.com/NguyenAntoine"],
        #["icon-twitter", "https://twitter.com/NguyenAntoine"],
        #["icon-facebook", "https://www.facebook.com/NguyenAntoine"],
        ["icon-linkedin", "https://linkedin.com/in/nguyen-antoine"]
      ]
